import os

SHOPIFY_STORE = os.getenv("SHOPIFY_STORE")
SHOPIFY_TOKEN = os.getenv("SHOPIFY_TOKEN")

FEISHU_APP_ID = os.getenv("FEISHU_APP_ID")
FEISHU_APP_SECRET = os.getenv("FEISHU_APP_SECRET")

BITABLE_APP_TOKEN = os.getenv("BITABLE_APP_TOKEN")
MAIN_TABLE_ID = os.getenv("MAIN_TABLE_ID")
SKU_TABLE_ID = os.getenv("SKU_TABLE_ID")

INSURANCE_SKUS = {
    "ROUTEINS",
    "SHIPPING-INSURANCE",
    "INSURANCE"
}
