import os

SHOPIFY_STORE = os.getenv("SHOPIFY_STORE")
SHOPIFY_TOKEN = os.getenv("SHOPIFY_TOKEN")

FEISHU_APP_ID = os.getenv("FEISHU_APP_ID")
FEISHU_APP_SECRET = os.getenv("FEISHU_APP_SECRET")

BITABLE_APP_TOKEN = "H3o5bIFfZaAQv6s7FlscEXsunFe"

MAIN_TABLE_ID = "tbl2CIOzMpokv4w0"

SKU_TABLE_ID = "tbl8yV5CM4ut8u1I"

INSURANCE_SKUS = {
    "ROUTEINS",
    "SHIPPING-INSURANCE",
    "INSURANCE"
}
